pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/Mythri532/Jenkins-new.git'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git url: "${REPO_URL}"
            }
        }

        stage('Debug Workspace') {
            steps {
                sh 'ls -R'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-jenkins', variable: 'KUBECONFIG')]) {
                    sh '''
                        kubectl apply -f my-first-pipeline/deployment.yaml
                        kubectl apply -f my-first-pipeline/service.yaml
                    '''
                }
            }
        }
    }
}
